# This is a program to trim down the total number of GPS logs generated by GPS_Demo.ino
# It will only keep every tenth log from the input file

# Input and output file paths
input_file = "GPS_Log.txt"
output_file = "GPS_Log_one-tenth.txt"

# Function to save every 10th line to the output file
def save_every_10th_line(input_path, output_path):
    with open(input_path, "r") as input_file, open(output_path, "w") as output_file:
        lines = input_file.readlines()
        for i in range(0, len(lines), 10):
            output_file.write(lines[i])

# Call the function to process the file
save_every_10th_line(input_file, output_file)

print("Every 10th line has been saved to", output_file)